### ISSUE TITLE
Turn encoder

### ISSUE THREAD

**Issue by ofersmi** [yastefan/grandMA3-Chataigne-Module#1]
Hello,
I have some issues setting up the turn encoders.
What do they expect as input? Endless or CC? 
In endless mode my controller sends out 63 when going down and 65 on up, but the state machine only checks on change/// 

Thank you

Ofer

**Comment by yastefan** [comment]
Hi,
`turn encoders` is for endless/relative inputs. In comparison, `move Fader` is for absolute inpus (CC). The behaviour that a controller uses `63` for turn down and `65` for turn up was not known to me. Turn encoder' expects negative values for turn down and positive values for turn up. So you should just be able to use a math filter with the value `- 64` :). Feel free to give me feedback if this works.

Stefan

**Comment by ofersmi** [comment]
Hello Again,
I might be misunderstanding something, I am not a Chataigne expert. I have created a mapping with midi cc in and "Turn Encoder" out (with a remap in the middle to have -/+) inside a State Machine. But then I only get a value out when I change direction and not on every turn.
Ofer

**Comment by pmjcontroller1** [comment]
> Hello Again,
> I might be misunderstanding something, I am not a Chataigne expert. I have created a mapping with midi cc in and "Turn Encoder" out (with a remap in the middle to have -/+) inside a State Machine. But then I only get a value out when I change direction and not on every turn.
> Ofer

test in the input CC right button "always changes"

**Comment by ofersmi** [comment]
That was it!@ 

Thanks
