### ISSUE TITLE
Addon to Module

### ISSUE THREAD

**Issue by PixelLighting** [yastefan/grandMA3-Chataigne-Module#11]
[module.zip](https://github.com/yastefan/grandMA3-Chataigne-Module/files/12525666/module.zip)

Hello i added Some Basic Encoders for The Programmer encoder section i only dont know how to add a Second Menu like Extra Encoder to have better oversight for like 1 Page For the Basics and Another one for Extra Encoders Like the animation wheel or second Prisma if its thier to keep the Dropdown menu Smaller

**Comment by yastefan** [comment]
I have included your suggested changes. I think that it remains clear enough. Thanks for your contribution
