### ISSUE TITLE
MIDI mapping keyboard button delay is high

### ISSUE THREAD

**Issue by 517002650** [yastefan/grandMA3-Chataigne-Module#15]
Midi mapping keyboard has a particularly large delay. How can we achieve button pressing and button talk, and can we achieve midi on signal keyboard button pressing and midi off signal button popping?

**Comment by PixelLighting** [comment]
i Never have any delay especialy with Midi controller its in Miliseconds so fast that i cant notice it it seems more like a Network(OSC) problem or you pc Struggels a bit or what can be you keyboard can be a problem too

**Comment by 517002650** [comment]
> 我从来没有任何延迟，尤其是 Midi 控制器，它的毫秒速度如此之快，以至于我无法注意到它，这似乎更像是网络 （OSC） 问题，或者您的 PC Struggels 有点，或者您的键盘也可能是一个问题

Can the MIDI signal be used to control the keyboard shortcut keys of MA3 by pressing large keyboard buttons and having the same effect as when keyboard buttons pop up?

**Comment by 517002650** [comment]
> i Never have any delay especialy with Midi controller its in Miliseconds so fast that i cant notice it it seems more like a Network(OSC) problem or you pc Struggels a bit or what can be you keyboard can be a problem too

The MIDI mapping to keyboard output indeed has a high latency, at least 500 milliseconds or more

**Comment by 517002650** [comment]
> i Never have any delay especialy with Midi controller its in Miliseconds so fast that i cant notice it it seems more like a Network(OSC) problem or you pc Struggels a bit or what can be you keyboard can be a problem too

It takes about 500 milliseconds to recognize the keyboard signal

**Comment by 517002650** [comment]
> 我从来没有任何延迟，尤其是 Midi 控制器，它的毫秒速度如此之快，以至于我无法注意到它，这似乎更像是网络 （OSC） 问题，或者您的 PC Struggels 有点，或者您的键盘也可能是一个问题



> 我从来没有任何延迟，尤其是 Midi 控制器，它的毫秒速度如此之快，以至于我无法注意到它，这似乎更像是网络 （OSC） 问题，或者您的 PC Struggels 有点，或者您的键盘也可能是一个问题



> > i Never have any delay especialy with Midi controller its in Miliseconds so fast that i cant notice it it seems more like a Network(OSC) problem or you pc Struggels a bit or what can be you keyboard can be a problem too
> 
> The MIDI mapping to keyboard output indeed has a high latency, at least 500 milliseconds or more

![7f52aea01da212efb69fb43befbca3b](https://github.com/yastefan/grandMA3-Chataigne-Module/assets/83255634/9efc7934-de79-4f9f-a546-2f6895e81020)


> i Never have any delay especialy with Midi controller its in Miliseconds so fast that i cant notice it it seems more like a Network(OSC) problem or you pc Struggels a bit or what can be you keyboard can be a problem too
![7f52aea01da212efb69fb43befbca3b](https://github.com/yastefan/grandMA3-Chataigne-Module/assets/83255634/88e6fa72-9304-4b50-9681-fa6a2ada0de7)



> i Never have any delay especialy with Midi controller its in Miliseconds so fast that i cant notice it it seems more like a Network(OSC) problem or you pc Struggels a bit or what can be you keyboard can be a problem too

![7f52aea01da212efb69fb43befbca3b](https://github.com/yastefan/grandMA3-Chataigne-Module/assets/83255634/db22d959-2c8c-41d0-9cbf-f486374fef08)
68/10000
实时翻译
68/10000 real-time translation 68/10000 real-time translation activation MIDI mapping keyboard button output will cause significant delay, rather than due to PC configuration issues. The CPU of the PC system runs at only 4% speed, and due to some unknown reason, the latency is very severe. If the mapping is not activated, the speed is very fast. Translating Activating MIDI mapping keyboard button output will result in significant delay, not due to PC configuration issues The CPU of the PC system is only running at 4%, and for some unknown reason, the delay is significant If the mapping is not activated, the speed is very fast

划译
Activating MIDI mapping keyboard button output will result in significant delay, not due to PC configuration issues. The CPU of the PC system is only running at 4%, and for some unknown reason, the delay is significant. If the mapping is not activated, the speed is very fast

**Comment by yastefan** [comment]
Hello 517002650,
actually I haven't seen the need to emulate keyboard keys to pass shortcuts to grandMA3. I personally program on a normal PC keyboard and get along well with the shortcuts. There is a TouchOSC interface that logs on to the PC as a keyboard and emulates the layout of the Commandwing, allowing programming outside the FoH. This may be of interest to you.

https://github.com/yastefan/GMA3_TouchOSC

I can't quite understand the delays and would rather look for the problem in the keyboard emulation than in the midi input

**Comment by PixelLighting** [comment]
i dont see the True mapping sorry i tried to have a mapping with a Learnd Input to convert and send into ma 0 delay tried it on my laptop and my pc never have any delays this seems more a you Problem as not nice as it sounds i dont know how you are mapping the buttons

**Comment by 517002650** [comment]
> i dont see the True mapping sorry i tried to have a mapping with a Learnd Input to convert and send into ma 0 delay tried it on my laptop and my pc never have any delays this seems more a you Problem as not nice as it sounds i dont know how you are mapping the buttons

I have found the location of the delay issue, which is caused by the latest version of Chataigne's keyboard module. I hope the Chataigne team can fix it as soon as possible. Everything is normal using version 1.9.5

**Comment by 517002650** [comment]
> 
> 我不太能理解延迟，宁愿在键盘仿真中寻找问题，也不愿在 midi 输入中寻找问题



> Hello 517002650, actually I haven't seen the need to emulate keyboard keys to pass shortcuts to grandMA3. I personally program on a normal PC keyboard and get along well with the shortcuts. There is a TouchOSC interface that logs on to the PC as a keyboard and emulates the layout of the Commandwing, allowing programming outside the FoH. This may be of interest to you.
> 
> https://github.com/yastefan/GMA3_TouchOSC
> 
> I can't quite understand the delays and would rather look for the problem in the keyboard emulation than in the midi input

Yes, but he doesn't support hardware MIDI devices, hey!

**Comment by yastefan** [comment]
If you want to familiarize yourself with TouchOSC, you can also use it to map MIDI input. In the project listed, a LaunchControl and a LaunchPAD are mapped to the executor faders and buttons in grandMA3. It is also possible to make a mapping for the program buttons without much effort. However, it is not interesting for me because I prefer to program in the FoH on the CommandWing or a PC keyboard.

Since it is an issue with the keyboard mapping, I will soon close the issue
