### ISSUE TITLE
Would you like to add a module to support MA2 control in the future?

### ISSUE THREAD

**Issue by 517002650** [yastefan/grandMA3-Chataigne-Module#17]
Ma2 can use macro commands to support roller encoder command control programming. If we add a module that supports remote control of MA2 in the future, it would be perfect

**Comment by yastefan** [comment]
In my opinion, this is more of a task for another Chataigne plugin. Chataigne provides small modules that have exactly one purpose. Another lighting console or software is therefore a task for another module. The synergies would not be great either, as the communication in grandMA3 runs via OSC and in grandMA2 via Midi or Telnet
