### ISSUE TITLE
Does the actuator pusher and button support flipping pages, and does this module support sending MA3 commands to MA3 onpc?

### ISSUE THREAD

**Issue by 517002650** [yastefan/grandMA3-Chataigne-Module#18]
I would like to know if this module supports sending commands from MA3 to MA3, controlling the pusher actuators, and whether these controls support page flipping. For example, if I only have 10 pushers and buttons, I can only control the push rods and buttons of the 10 actuators on Page 1? How do my 10 pushers and buttons control the actuator pushers and buttons of Page 2-10?

**Comment by yastefan** [comment]
Hello,
this is not a forum. You are opening tickets saying that this Chataigne plugin has a problem that needs to be fixed. Your questions are better placed here:
https://discord.gg/wYNB3rK
But briefly: Yes, you can send commands to grandMA3 with the plugin and with these you can change the current page
