### ISSUE TITLE
Encoders exectutors

### ISSUE THREAD

**Issue by pmjcontroller1** [yastefan/grandMA3-Chataigne-Module#2]
hello yastefan. 
 thanks for the module you have written it is fantastic. 

 I have a query that complement you have thought for the encoders that are in the executors. 

 Could you help me with that plugin for a 1, 127 encoder?

**Comment by yastefan** [comment]
Hello pmjcontroller1,

sorry for the late reply, I just got back from holiday. I don't think I quite understand your question yet. What do you want to do specifically? If you want to change the values of executors with absolute faders (0-127) you can use `Move Executor Fader`.

Best regards
Stefan

**Comment by pmjcontroller1** [comment]
> Hello pmjcontroller1,
> 
> sorry for the late reply, I just got back from holiday. I don't think I quite understand your question yet. What do you want to do specifically? If you want to change the values of executors with absolute faders (0-127) you can use `Move Executor Fader`.
> 
> Best regards
> Stefan

hi yastefan.  It's okay for the delay, I hope your vacation was pleasant.  I will try to explain myself.  I need to control the executing rotary encoders 301 , 401  etc.  For this I have a MIDI controller built by us, with several encoders that send MIDI CC with value 1 when it turns left and value 127 when it turns right.  I can't find an option so that with each value 127 the value of the executor increases by +1 and with each value 1 I decrease -1 in the value of the executor.  I hope I have explained my doubt and that you can help me.

**Comment by yastefan** [comment]
All right. In grandMA3 there are two ways to use the upper rotary encoders. You can control them as absolute faders (0 - 127) and that should work in a workaround. You can create a `custom variable` in Chataigne, which you increment or decrement via an `action`. You can then map the `custom variable` via the grandMA3 plug-in.

The other possibility is to send grandMA3 encoder commands directly. I will integrate this option into the plugin soon. Thanks for your feedback :)

**Comment by pmjcontroller1** [comment]
> All right. In grandMA3 there are two ways to use the upper rotary encoders. You can control them as absolute faders (0 - 127) and that should work in a workaround. You can create a `custom variable` in Chataigne, which you increment or decrement via an `action`. You can then map the `custom variable` via the grandMA3 plug-in.
> 
> The other possibility is to send grandMA3 encoder commands directly. I will integrate this option into the plugin soon. Thanks for your feedback :) 

ok perfect 
I hope that update soon, 
while you can help me with the mapping in Chataigne to make the custom variable because I can't configure it. 

 I will also send you this afternoon a change that we made in your code about the attribute encoders adding a solution because we could not configure it for you to study

**Comment by pmjcontroller1** [comment]
hello.  how are you doing with the update?

**Comment by yastefan** [comment]
The module now has the possibility to use the encoder functionality in grandMA3 via `Turn Executor Encoder`. It took me a while because I didn't have a midi controller with endless encoders. After I bought a MidiFighter Twister, I was dissatisfied with the possibility to map the values easily. 

That's why this module was created:
https://github.com/yastefan/MidiEncoder-Chataigne-Module

Maybe it will help you too

**Comment by pmjcontroller1** [comment]
> The module now has the possibility to use the encoder functionality in grandMA3 via `Turn Executor Encoder`. It took me a while because I didn't have a midi controller with endless encoders. After I bought a MidiFighter Twister, I was dissatisfied with the possibility to map the values easily. 
> 
> That's why this module was created:
> https://github.com/yastefan/MidiEncoder-Chataigne-Module
> 
> Maybe it will help you too

great and stefan.  you could have said it and we can send you one for testing, count on us next time.  this afternoon we tested the new code
