### ISSUE TITLE
Possible bug with the encoders

### ISSUE THREAD

**Issue by jrcks** [yastefan/grandMA3-Chataigne-Module#3]
I have been using the [Behringer X-Touch Compact](https://www.thomann.de/de/behringer_x_touch_compact.htm) with onPC 1.8.8.2 and wanted to program the encoders.

I noticed, that the values being send were only 0 or 1 while the input values where 1 or 65. So I changed the line 
https://github.com/yastefan/grandMA3-Chataigne-Module/blob/28d41b17c8f501f219cd6e991bcbaad5a4fc8567/grandMA3.js#L82
to
``` js
function turnEncoder(encoder, unknown, multiplicator, value) {
    ...
}
```
which fixed the issue. I don't know much about Chataigne so the 2nd parameter is unkown for me but I suspect it being the boolean?

**Comment by yastefan** [comment]
Hey Julian,
thank you for your feedback. The parameter was once intended to be able to change values of the encoder bar not only with endless encoders, but also with absolute values. However, I now think that this is more likely to cause confusion and have removed the parameter.

Stefan
