### ISSUE TITLE
 Mapping expansion proposal

### ISSUE THREAD

**Issue by pmjcontroller1** [yastefan/grandMA3-Chataigne-Module#4]
Hi Yestefan.
I'm thinking of making a controller that has the buttons of a comnadwing, the right part. It would have all the keys, the 5 double encoders that can already be mapped, the 2 faders, the circular fader, and the 10 small encoders.
Have you thought if these controls could be mapped by osc?
![15057455_800](https://user-images.githubusercontent.com/118101014/236168070-1e8360d5-8151-443f-88ed-427bb887a4fe.jpg)

**Comment by yastefan** [comment]
Hello pmjcontroller1,

the mapping of the command section should be possible via keyboard shortcuts. This project here 
https://github.com/yastefan/GMA3_TouchOSC
(forked from imhofroger) does exactly that. It activates the shortcuts (F10) for each keystroke, executes the key combination and deactivates the shortcuts again. If you want to perform such a function with a microcontroller, it should implement two USB drivers: one midi and one HID device. 

However, I find the idea of rebuilding a CommandWing at least borderline. For one thing, MA might not find it funny. On the other hand, the limiting interfaces (encoders are not responsive and you can't easily assign executors) won't give it the quality to be used live, and at home I'm similarly fast with the keyboard.

As a hobby project it might be okay, but as a product I wouldn't build such a controller.

I hope this helps you

**Comment by pmjcontroller1** [comment]
Great was just a possibility, a thought I was happy to share with you. You help me a lot with your vision.
Thanks for your answer
